#!/usr/bin/env ruby

require 'date'
require 'json'

data = {
  host:  ENV['DIRVISH_CLIENT'],
  tree:  ENV['DIRVISH_SRC'],
  state: ENV['DIRVISH_STATUS'],
  date:  DateTime.now.strftime('%Y/%m/%d %H:%M:%S')
}.to_json

STDERR.puts(data)
